// Build a self-contained docs/index.html for hosting (GitHub Pages publishes from /docs).
//
// Run:  osascript -l JavaScript build.js
//
// index.html is the source of truth: it compiles JSX in the browser via Babel, which
// keeps it a no-build-step file you can just open. The cost is 2.8 MB of Babel, which
// is a lot to send to a phone on mobile data — and the compilation is pointless once
// the code has stopped changing.
//
// So this pre-compiles the JSX with the same Babel and inlines React, emitting one
// ~145 KB HTML file with no external references at all. Upload it anywhere; it needs
// no server-side anything. Do not edit docs/index.html — edit index.html and rebuild.

ObjC.import("Foundation");

function read(path) {
  const contents = $.NSString.stringWithContentsOfFileEncodingError(path, $.NSUTF8StringEncoding, null);
  if (!contents.js) throw new Error("could not read " + path);
  return contents.js;
}

function write(path, text) {
  const ok = $.NSString.alloc
    .initWithUTF8String(text)
    .writeToFileAtomicallyEncodingError(path, true, $.NSUTF8StringEncoding, null);
  if (!ok) throw new Error("could not write " + path);
}

const fileManager = $.NSFileManager.defaultManager;
const cwd = fileManager.currentDirectoryPath.js;
const ROOT = fileManager.fileExistsAtPath(cwd + "/index.html") ? cwd : cwd + "/..";

const source = read(ROOT + "/index.html");

// Compile the JSX exactly as the browser would, using the vendored Babel.
(0, eval)(read(ROOT + "/vendor/babel.min.js"));
const jsxMatch = source.match(/<script type="text\/babel"[^>]*>([\s\S]*?)<\/script>/);
if (!jsxMatch) throw new Error("could not find the text/babel block in index.html");
const compiled = Babel.transform(jsxMatch[1], { presets: ["react"] }).code;

// Replacement strings are passed as functions: the minified React bundles are full of
// `$$`, which would otherwise be mangled by the special patterns in String.replace.
const inlineScript = (id, js) => () => '<script id="' + id + '">\n' + js + "\n</script>";

let out = source;

// Swap the three <script src> tags for React inlined, and drop Babel entirely.
out = out.replace(
  /<script src="vendor\/react\.production\.min\.js"><\/script>\s*<script src="vendor\/react-dom\.production\.min\.js"><\/script>\s*<script src="vendor\/babel\.min\.js"><\/script>/,
  inlineScript(
    "flicker-vendor",
    read(ROOT + "/vendor/react.production.min.js") + "\n" + read(ROOT + "/vendor/react-dom.production.min.js")
  )
);
if (out.indexOf("vendor/") !== -1) throw new Error("a vendor/ reference survived the build");

// Swap the JSX block for its compiled output. The id lets test/boot.test.js find and
// verify the built file, not just the source.
out = out.replace(/<script type="text\/babel"[^>]*>[\s\S]*?<\/script>/, inlineScript("flicker-app", compiled));
if (out.indexOf("text/babel") !== -1) throw new Error("the text/babel block survived the build");

out =
  "<!-- Generated by build.js from index.html. Do not edit: your changes will be overwritten. -->\n" +
  out;

// ---- verify the artefact before declaring victory ----
const problems = [];
if (!/React\.createElement/.test(out)) problems.push("compiled JSX is missing (no React.createElement calls)");
if (/<[A-Za-z]+ className=/.test(compiled)) problems.push("uncompiled JSX survived the transform");
if (!/id="flicker-core"/.test(out)) problems.push("the flicker-core block is missing");
if (!/id="root"/.test(out)) problems.push("the #root mount point is missing");
if (!/reportBootFailure/.test(out)) problems.push("the boot-failure reporter is missing");
if (/src="/.test(out)) problems.push("an external reference survived; the file is not self-contained");
if (problems.length) throw new Error("build produced a broken file:\n  " + problems.join("\n  "));

fileManager.createDirectoryAtPathWithIntermediateDirectoriesAttributesError(ROOT + "/docs", true, $.null, null);
write(ROOT + "/docs/index.html", out);

const sourceKb = Math.round((source.length + 2949000) / 1024); // source + the vendor/ it loads
const distKb = Math.round(out.length / 1024);
"built docs/index.html — " + distKb + " KB, self-contained (was ~" + sourceKb + " KB with Babel)";
